language: python
python: 2.7

sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

env:
  - TOX_ENV=py27-1.8.X
  - TOX_ENV=py27-1.7.X
  - TOX_ENV=py27-1.6.X
  - TOX_ENV=py27-1.5.X
  - TOX_ENV=py34-1.8.X
  - TOX_ENV=py34-1.7.X
  - TOX_ENV=py34-1.6.X
  - TOX_ENV=py34-1.5.X
  - TOX_ENV=docs
  - TOX_ENV=flake8

install:
  - pip install tox --cache-dir $HOME/.pip-cache

script:
  - tox -e $TOX_ENV

after_success:
  coveralls
